# -*- coding: utf-8 -*-
"""Queue_Stack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eQv2QkYLy8KqLz5PgNCrVLYRAUgxdKds
"""

class MyQueue:

    def __init__(self):
        
        self.enqueue = []
        self.dequeue = []     

    def push(self, x: int) -> None:
        self.enqueue.append(x)
        
    def move(self)-> None:
        while self.enqueue:
            self.dequeue.append(self.enqueue.pop())        

    def pop(self) -> int:
        
        if not self.dequeue:
            self.move()
        return self.dequeue.pop()
        
    def peek(self) -> int:
        if not self.dequeue:
            self.move()
        return self.dequeue[-1]
        

    def empty(self) -> bool:
        return not len(self.enqueue) and not len(self.dequeue)